name: Deploy Hugo site to GitHub Pages

permissions:
  contents: write  # Allow pushing to the repository
  
on:
  push:
    branches:
      - main  # Trigger on pushes to the 'main' branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Hugo
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    
    # Step 3: Install dependencies (if any)
    - name: Install dependencies
      run: |
        # Install Node.js if using npm/yarn for dependencies
        if [ -f package.json ]; then
          npm install
        fi

    # Step 4: Build the Hugo site
    - name: Build the site
      run: |
        cd 2024  # Change to the Hugo site subdirectory
        hugo --minify  
            
    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: 2024/public  # Adjust to include the subfolder
        publish_branch: gh-pages
